from pathlib import Path

from mcp.server.fastmcp import FastMCP

# Initialize FastMCP server
mcp = FastMCP(
    "poweranalytics",
    instructions="""
    You are a helpful assistant for analyzing power system simulation results using
    PowerAnalytics.jl — a Julia package that operates on results generated by
    PowerSimulations.jl with data structures from PowerSystems.jl.

    PowerAnalytics runs locally via the Julia REPL. There are no remote API calls.
    Your workflow when a user requests analysis is:
    1. Activate the Julia REPL and the project environment.
    2. Generate a Julia script that uses the PowerAnalytics.jl public API.
    3. Execute the script in the REPL.
    4. Save results to a data file when appropriate.
    5. Analyze the output and explain the results back to the user.

    When writing Julia code:
    - Use only functions, types, and methods from the PowerAnalytics.jl public API.
    - Activate the correct project environment before running any code.
    - Handle errors gracefully and report them clearly.

    When explaining results:
    - Provide context in terms of power system operations and economics.
    - Include units (MW, MWh, $/MWh, etc.) with all numeric values.
    - Summarize trends and highlight noteworthy observations.
    """,
)

# Paths — configure these to match the local environment
JULIA_EXECUTABLE = "julia"  # path to Julia binary, or just "julia" if on PATH
PA_PROJECT_PATH = Path(".")  # placeholder — path to the PowerAnalytics.jl project


# ---------------------------------------------------------------------------
# Tools, resources, and prompts will be added here.
#
# Examples of future tools:
#   - run_julia_script: Execute a Julia script in the REPL
#   - activate_project: Activate the PowerAnalytics.jl project environment
#
# Examples of future resources:
#   - PowerAnalytics.jl public API reference
#   - Available simulation result datasets
#
# Examples of future prompts:
#   - Standard analysis templates (e.g. generation by fuel type, cost breakdown)
# ---------------------------------------------------------------------------


def main():
    mcp.run(transport="stdio")


if __name__ == "__main__":
    main()
