import ssl
from typing import Any

import httpx
import truststore
from mcp.server.fastmcp import FastMCP

# Initialize FastMCP server
mcp = FastMCP(
    "poweranalytics",
    instructions="""
    You are a helpful assistant for analyzing power system simulation results using PowerAnalytics.

    PowerAnalytics is a Julia package designed to analyze and interpret results from power system
    simulations (generated by PowerSimulations.jl). It provides tools for:
    - Analyzing simulation results from production cost models and capacity expansion studies
    - Collecting, aggregating, and subsetting simulation data
    - Interpreting power system metrics (generation, costs, flows, utilization, etc.)

    Use the available tools to help users:
    - Query and retrieve simulation results
    - Aggregate data across time periods, regions, or asset categories
    - Interpret and summarize power system behavior and economics
    - Prepare data for visualization and reporting

    Always explain results in the context of power system operations and economics.
    When presenting numeric results (e.g. costs, generation, capacity), include units and context.
    """,
)

# Constants
PA_API_BASE = "https://api.poweranalytics.sienna.example.com"  # placeholder — replace with real base URL
USER_AGENT = "poweranalytics-mcp/1.0"

# Use OS trust store (macOS Keychain / Windows cert store) for SSL verification
SSL_CTX = truststore.SSLContext(ssl.PROTOCOL_TLS_CLIENT)


async def make_pa_request(
    url: str,
    method: str = "GET",
    json: dict[str, Any] | None = None,
    headers: dict[str, str] | None = None,
) -> dict[str, Any] | None:
    """Make a request to the PowerAnalytics API with proper error handling."""
    default_headers = {
        "User-Agent": USER_AGENT,
        "Accept": "application/json",
        "Content-Type": "application/json",
    }
    if headers:
        default_headers.update(headers)

    async with httpx.AsyncClient(verify=SSL_CTX) as client:
        try:
            response = await client.request(
                method, url, headers=default_headers, json=json, timeout=30.0
            )
            response.raise_for_status()
            return response.json()
        except Exception as e:
            print(f"Error calling {method} {url}: {type(e).__name__}: {e}")
            return None


# ---------------------------------------------------------------------------
# Tools, resources, and prompts will be added here.
# ---------------------------------------------------------------------------


def main():
    mcp.run(transport="stdio")


if __name__ == "__main__":
    main()
